AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'define', 'factory']

Lint/MissingSuper:
  Exclude:
    - 'lib/pricing_rules/*'

